# This file was generated by GoReleaser. DO NOT EDIT.
cask "docker-hash" do
  version "0.3.15"

  on_macos do
    on_intel do
      url "https://github.com/RemkoMolier/docker-hash/releases/download/v#{version}/docker-hash_#{version}_darwin_amd64.tar.gz"
      sha256 "9b86253f7ce3c3720c70eb1f831f6d69900c3763ac850be3c715c92c0ebb5807"
    end
    on_arm do
      url "https://github.com/RemkoMolier/docker-hash/releases/download/v#{version}/docker-hash_#{version}_darwin_arm64.tar.gz"
      sha256 "affcd403c5f159fb09e6dc758bf8bf81a7a3f17f5b60760a6fa76860e8eb570a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/RemkoMolier/docker-hash/releases/download/v#{version}/docker-hash_#{version}_linux_amd64.tar.gz"
      sha256 "f0f5f184cdde3dfdb75209ce789bdc70905344859f230218d6dc64c68d54585c"
    end
    on_arm do
      url "https://github.com/RemkoMolier/docker-hash/releases/download/v#{version}/docker-hash_#{version}_linux_arm64.tar.gz"
      sha256 "44f4977bc3057c3f6a8c2bff3b604c63d0f7f33e75cab6fb87d94aba2c0a5f9a"
    end
  end

  name "docker-hash"
  desc "Compute a deterministic SHA-256 hash for Docker image builds"
  homepage "https://github.com/RemkoMolier/docker-hash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "docker-hash"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/docker-hash"]
    end
  end

  # No zap stanza required

end
