# This file was generated by GoReleaser. DO NOT EDIT.
cask "docker-hash" do
  version "0.3.10"

  on_macos do
    on_intel do
      url "https://github.com/RemkoMolier/docker-hash/releases/download/v#{version}/docker-hash_#{version}_darwin_amd64.tar.gz"
      sha256 "b154f813c23c871c7f920639278bf4e319b88ff65a9ace7b432621008b65698f"
    end
    on_arm do
      url "https://github.com/RemkoMolier/docker-hash/releases/download/v#{version}/docker-hash_#{version}_darwin_arm64.tar.gz"
      sha256 "5e2a365ef2bd4bdc2a71164915864e91b0aa0cd89c115abd02a295a629e0eb6f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/RemkoMolier/docker-hash/releases/download/v#{version}/docker-hash_#{version}_linux_amd64.tar.gz"
      sha256 "b263cc817722d00ee95126b202119345f7b15d5443b3f0cb04a7f1982e223b27"
    end
    on_arm do
      url "https://github.com/RemkoMolier/docker-hash/releases/download/v#{version}/docker-hash_#{version}_linux_arm64.tar.gz"
      sha256 "e58c8d22a9a1c09b7a53097396328861983178fda711d2b4570f111d8ac60007"
    end
  end

  name "docker-hash"
  desc "Compute a deterministic SHA-256 hash for Docker image builds"
  homepage "https://github.com/RemkoMolier/docker-hash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "docker-hash"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/docker-hash"]
    end
  end

  # No zap stanza required

end
