# This file was generated by GoReleaser. DO NOT EDIT.
cask "docker-hash" do
  version "0.3.26"

  on_macos do
    on_arm do
      sha256 "7ea3c6ca638461e706edffa56984c7ed12a9d73c79b292a152cd7b7959fee0c6"
      url "https://github.com/RemkoMolier/docker-hash/releases/download/v#{version}/docker-hash_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "800ab13e4fca38f9eac47961d5e91f2350af02932d26e563b5902fe018dea576"
      url "https://github.com/RemkoMolier/docker-hash/releases/download/v#{version}/docker-hash_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d80d07492653f859e1a6cbf0513ec840224cbc7ac4080efb09314ced28ce0f41"
      url "https://github.com/RemkoMolier/docker-hash/releases/download/v#{version}/docker-hash_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1f6a581827bcb23c8e74838b8912c514554bea2406d5f887164065f3d06f89fa"
      url "https://github.com/RemkoMolier/docker-hash/releases/download/v#{version}/docker-hash_#{version}_linux_amd64.tar.gz"
    end
  end

  name "docker-hash"
  desc "Compute a deterministic SHA-256 hash for Docker image builds"
  homepage "https://github.com/RemkoMolier/docker-hash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "docker-hash"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/docker-hash"]
    end
  end

  # No zap stanza required
end
